"""empty message

Revision ID: 9f102f752931
Revises: 1f6b164ec0ce
Create Date: 2026-07-19 14:46:12.939938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f102f752931'
down_revision: Union[str, Sequence[str], None] = '1f6b164ec0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attachments_file_key'), table_name='attachments')
    op.create_unique_constraint(None, 'attachments', ['file_key'])
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_constraint(None, 'attachments', type_='unique')
    op.create_index(op.f('ix_attachments_file_key'), 'attachments', ['file_key'], unique=True)
    # ### end Alembic commands ###
